apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32605
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31775
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: wordpress
  type: LoadBalancer
